### ISSUE TITLE
Speed issues

### ISSUE THREAD

**Issue by riemervdzee** [riemervdzee/hero-kernel-2.6.35_OLD#6]
We lack some speed, especially at drawing things... neocore score is around 23 fps while we can get 35 fps on .29 easily

**Comment by Elemag** [comment]
All graphics are rendered at exactly half rate compared to the 2.6.34 kernel.
Maybe a duplicate somewhere?

**Comment by riemervdzee** [comment]
What did you use for testing this? But there is something off aye...

**Comment by riemervdzee** [comment]
Btw, since some time the ram-console opens up properly. Some config thingies (I hate creating configs btw.. always no clue what to select).

Maybe that early-printk of yours now work?

**Comment by Elemag** [comment]
I ran various benchmarks -- Neocore, Quadrant, An3DBench and almost whatever I found in market numerous times.

Enabling debug_ll and early_printk result in early crash. With debug_ll it works a few msecs more.

**Comment by riemervdzee** [comment]
Seems you are right quite some time ago. There was something wrong with displaying, which is fixed at:
https://github.com/riemervdzee/cm-kernel/commit/1a6e2d91086226fd939439dd006ca2a56db35b2a

Still the kernel is not that fast like the .29 one, however it is way better than before :) Neocore score is now at 33 fps. 
The patch hardly had any influence at linpack though, so there is something missing.
