### ISSUE TITLE
Can't reboot into recovery/fastboot when kernel is used in a ROM

### ISSUE THREAD

**Issue by riemervdzee** [riemervdzee/hero-kernel-2.6.35_OLD#8]
You can boot into recovery or fastboot by using the key-commands when the device is powered off.
It seems I am the only one who gets this problem when booted fully into a ROM (while some others do not have this problem?)

**Comment by Elemag** [comment]
I surely don't

**Comment by riemervdzee** [comment]
as in: you don't have this problem? :P

**Comment by Elemag** [comment]
As in "I don't have that problem for sure" :)

**Comment by riemervdzee** [comment]
Don't have this problem anymore, all of the sudden. Strange... Will close it after a few tests.
